export const APP_ROUTES = {
  root: "/",
  login: "/auth/login",
  forget_password: "/auth/forget-password",
  createProgram: "/app/programs/create",
  myPrograms: "/app/programs/my-programs",

  dashboard: "/app/dashboard",
  programs: "/app/programs",
  programsInternal: "/app/programs/internal",
  programsSpiff: "/app/programs/spiff",
  programsSpiffInternal: "/app/programs/spiff/internal",
  programsSalesManager: "/app/programs/sales-manager",
  programsSalesManagerInternal: "/app/programs/sales-manager/internal",
  productInsights: "/app/product-insights",
  products: "/app/products",
  storePrograms: "/app/programs/store",
  storeProgramsInternal: "/app/programs/store/internal",
  chainPrograms: "/app/programs/chain",
  chainProgramsInternal: "/app/programs/chain/internal",
  finance: "/app/finance",
  users: "/app/users",
  account: "/app/account",
  editProfile: "/app/account/edit-profile",
  changePassword: "/app/account/change-password",
  store: "/app/store",
  storeChains: "/app/store/chains",
  storeSpiff: "/app/store/spiff",
  storeDashboard: "/app/dashboard",
  storeWishlist: "/app/wishlist",
  storeInternal: "/app/store/internal",
  distributorAdmin: "/app/distributor-admin",
  distributorAdminPrograms: "/app/distributor-admin/programs"
};
