export const USER_STATUS = {
  INVITATION_PENDING: "INVITATION_PENDING",
  INVITATION_SENT: "INVITATION_SENT",
  CHAIN_INVITATION_SENT: "CHAIN_INVITATION_SENT",
  CHAIN_ACTIVE: "CHAIN_ACTIVE",
  ACTIVE: "ACTIVE",
  DEACTIVE: "DEACTIVE"
};
