export const USER_ROLES = {
  MANUFACTURER: "MANUFACTURER", // "MANUFACTURER" is "MANUFACTURER_ADMIN"
  MANUFACTURER_EXECUTIVE: "MANUFACTURER_EXECUTIVE",
  MANUFACTURER_SALES_REP: "MANUFACTURER_SALES_REP",
  MANUFACTURER_ACCOUNT_MANAGER: "MANUFACTURER_ACCOUNT_MANAGER",
  DISTRIBUTOR_ADMIN: "DISTRIBUTOR_ADMIN",
  DISTRIBUTOR_EXECUTIVE: "DISTRIBUTOR_EXECUTIVE",
  DISTRIBUTOR_SALES_REP: "DISTRIBUTOR_SALES_REP",
  DISTRIBUTOR_GENERAL_MANAGER: "DISTRIBUTOR_GENERAL_MANAGER",
  DISTRIBUTOR_SALES_MANAGER: "DISTRIBUTOR_SALES_MANAGER",
  STORE: "STORE",
  SUPER_ADMIN: "SUPER_ADMIN"
};

export const USER_ROLES_INFO: any = {
  [USER_ROLES.MANUFACTURER]: "Manufacturer Admin",
  [USER_ROLES.MANUFACTURER_EXECUTIVE]: "Executive",
  [USER_ROLES.MANUFACTURER_SALES_REP]: "Sales Executive",
  [USER_ROLES.MANUFACTURER_ACCOUNT_MANAGER]: "Account Manager",
  [USER_ROLES.DISTRIBUTOR_ADMIN]: "Distributor Admin",
  [USER_ROLES.DISTRIBUTOR_EXECUTIVE]: "Executive",
  [USER_ROLES.DISTRIBUTOR_SALES_REP]: "Sales Executive",
  [USER_ROLES.DISTRIBUTOR_GENERAL_MANAGER]: "General Manager",
  [USER_ROLES.DISTRIBUTOR_SALES_MANAGER]: "Sales Rep Manager",
  [USER_ROLES.STORE]: "Store",
  [USER_ROLES.SUPER_ADMIN]: "Super Admin"
};
