import { ENTITY_TYPE } from "./appConstants";

// Define base route access
export const baseRouteAccess: Record<string, string[]> = {
  "/dashboard": [
    ENTITY_TYPE.MANUFACTURER,
    ENTITY_TYPE.MANUFACTURER_EXECUTIVE,
    ENTITY_TYPE.MANUFACTURER_ACCOUNT_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_SALES_REP,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER
  ],
  "/auth": [
    ENTITY_TYPE.MANUFACTURER,
    ENTITY_TYPE.MANUFACTURER_EXECUTIVE,
    ENTITY_TYPE.MANUFACTURER_ACCOUNT_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_SALES_REP,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER,
    ENTITY_TYPE.STORE,
    ENTITY_TYPE.CHAIN_ADMIN,
    ENTITY_TYPE.SUPER_ADMIN
  ],
  "/user": [
    ENTITY_TYPE.MANUFACTURER,
    ENTITY_TYPE.MANUFACTURER_EXECUTIVE,
    ENTITY_TYPE.MANUFACTURER_ACCOUNT_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_SALES_REP,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER,
    ENTITY_TYPE.STORE,
    ENTITY_TYPE.SUPER_ADMIN,
    ENTITY_TYPE.CHAIN_ADMIN
  ],
  "/programs": [
    ENTITY_TYPE.MANUFACTURER,
    ENTITY_TYPE.MANUFACTURER_EXECUTIVE,
    ENTITY_TYPE.MANUFACTURER_ACCOUNT_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_SALES_REP,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER,
    ENTITY_TYPE.STORE,
    ENTITY_TYPE.CHAIN_ADMIN
  ],
  "/store": [
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_SALES_REP,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER,
    ENTITY_TYPE.STORE,
    ENTITY_TYPE.MANUFACTURER,
    ENTITY_TYPE.MANUFACTURER_EXECUTIVE,
    ENTITY_TYPE.MANUFACTURER_ACCOUNT_MANAGER
  ],
  "/chain": [
    ENTITY_TYPE.CHAIN_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_SALES_REP,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER,
    ENTITY_TYPE.STORE,
    ENTITY_TYPE.MANUFACTURER,
    ENTITY_TYPE.MANUFACTURER_EXECUTIVE,
    ENTITY_TYPE.MANUFACTURER_ACCOUNT_MANAGER
  ],
  "/wishlist": [
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_SALES_REP,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER,
    ENTITY_TYPE.STORE,
    ENTITY_TYPE.MANUFACTURER,
    ENTITY_TYPE.MANUFACTURER_EXECUTIVE,
    ENTITY_TYPE.MANUFACTURER_ACCOUNT_MANAGER
  ],
  "/sales-rep": [
    ENTITY_TYPE.DISTRIBUTOR_SALES_REP,
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER
  ],
  "/manufacturer": [
    ENTITY_TYPE.MANUFACTURER,
    ENTITY_TYPE.MANUFACTURER_EXECUTIVE,
    ENTITY_TYPE.MANUFACTURER_ACCOUNT_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER
  ],
  "/distributor": [
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER
  ],
  "/program-approvals": [
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER,
    ENTITY_TYPE.STORE
  ],
  "/orders": [
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_SALES_REP,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER
  ],
  "/cart": [ENTITY_TYPE.DISTRIBUTOR_SALES_REP],
  "/distributor-admin": [ENTITY_TYPE.SUPER_ADMIN],
  "/agreements": [
    ENTITY_TYPE.MANUFACTURER,
    ENTITY_TYPE.MANUFACTURER_EXECUTIVE,
    ENTITY_TYPE.MANUFACTURER_ACCOUNT_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_ADMIN,
    ENTITY_TYPE.DISTRIBUTOR_EXECUTIVE,
    ENTITY_TYPE.DISTRIBUTOR_SALES_REP,
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER,
    ENTITY_TYPE.DISTRIBUTOR_SALES_MANAGER,
    ENTITY_TYPE.STORE,
    ENTITY_TYPE.CHAIN_ADMIN
  ]
};

// Define full route access
export const routeAccessControl: Record<string, string[]> = {
  "POST /distributor/product-insights": [
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER
  ],
  "GET /distributor/get-manager-warehouses": [
    ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER
  ],
  "GET /manufacturer/get-products": [ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER],
  "GET /manufacturer/skus-per-store": [ENTITY_TYPE.DISTRIBUTOR_GENERAL_MANAGER],
  "GET /distributor/spiff-summary": [ENTITY_TYPE.DISTRIBUTOR_SALES_REP]
};
